### PR TITLE
feat: double click to open NSFW media

### PR DESCRIPTION
**Pull request by qwreey75**
## What

Add option to change nsfw media open behavior: double click to open NSFW media

SmartSelect_20231103_045830_Kiwi Browser

## Why

To prevent mistakely open NSFW media

## Checklist
- [x] Read the [contribution guide](https://github.com/kokonect-link/cherrypick/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

### CODE REVIEW

**Comment by qwreey75** [comment]
Also should applied to video component (i will update pr when i can)

**Comment by qwreey75** [comment]
- [x] MkMediaVideo
- [x] MkMediaImage

https://github.com/kokonect-link/cherrypick/assets/46598063/7bcc2f87-c546-49d3-bc66-16f1c8c7f4d6

**Comment by qwreey75** [comment]
Note: Modifying clickedIndex to -1 is safe way to block opening PhotoSwipe. have no side-effects (packages/frontend/src/components/MkMediaList.vue)
Copied_Item_1698969277884

**Comment by noridev** [comment]
🙏🙏🙏

**Pull request merged**
